### ISSUE TITLE
V3.1 - right click on minimized icon also drags icon

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#10]
Right clicking on the minimized icon shows the "do you want to start up...."  message and also allows to drag the icon. So when moving the mouse pointer onto one of the buttons also moves the icon.

**Comment by AndyPiddock** [comment]
I cannot replicate this.
Can you please paste your system details from the window after hitting the bug reports button.
I can also add a pass for the right click to see if that helps.

**Comment by matthiasrebbe** [comment]
lc version 9.0.2
 os version 10.13.6
 seth version 3.1

Just to be clearer i´ve made a screen recording. See here http://d.qck.biz/hMuqiX

I pressed right click and released the button immediately. The answer dialog opened, but the icon still could be dragged. When i moved the mouse faster, the icon "lost focus" or what ever this is called and i was able to move the mouse without moving the icon. When i hovered over the icon, the icon again could be moved. This all happened without any mouse button  pressed.

**Comment by matthiasrebbe** [comment]
Btw. I´ve got rid of this by adding
   put false into sgDragging
to the script of image Seth-Logo-V3.png


on mouseUp pBtnNum
   if pBtnNum is 3 then
      put false into sgDragging
      if the height of this stack < 50 then
         answer "do you want to start up Seth minimized" with "Yes" and "No" and "Cancel"
         if it is "Yes" then
            set the SethStartUpMinimized of this stack to "yes"
            set the SethLastLoc of this stack to the topLeft of this stack
            put false into sgDragging

**Comment by AndyPiddock** [comment]
Thanks and Ha..just added exactly the same..great minds and all that. Interesting that I cannot get this to happen on Windows?

OK closing this its in for V3.2
