### ISSUE TITLE
Startup Options

### ISSUE THREAD

**Issue by macMikey** [AndyPiddock/Seth#13]
Help text says that right-clicking shows startup options.

1. Right-clicking only works if SETH is iconized
2. I'd like an option to start SETH without even the icon showing.

**Comment by AndyPiddock** [comment]
1. Ok in the tool tip text ..thanks will be corrected for V3.2
2 This would become confusing. How about being able to change the opacity to 90%? it would be barely noticeable then but you would still be able to tell that its open.

**Comment by AndyPiddock** [comment]
Included in V3.2 release.
