### ISSUE TITLE
Panel listing methods in IDE is all black

### ISSUE THREAD

**Issue by lazlo2424** [AndyPiddock/Seth#2]
Hi
I have installed the plugin and it works nicely in the main editor windows but the left panel that lists the method has black ink on a black background with only the highlighted method readable.  Is there a trick I need to do to make it work.

**Comment by AndyPiddock** [comment]
Hi , yes this is an issue that been reported several times and happens with black background themes. 
I am in the final testing stages of an all new version 3. This version now automatically determines if the handlers field  on the  left should have white or black text based on the background chosen. I am hoping to release the new version at the end of January. 
If you would like to test a pre-release version then please email me at sales@2108.co.uk using your original purchase email address.

![sethv3](https://user-images.githubusercontent.com/37116306/51442202-ac428680-1cda-11e9-9019-f643cf9b5e11.png)


![2019-01-20_17-37-40](https://user-images.githubusercontent.com/37116306/51442149-33432f00-1cda-11e9-808c-a2dcf8713be7.png)

Andy

**Comment by AndyPiddock** [comment]
Fixed in release of V3.0
