### ISSUE TITLE
Feature request: Allow minimized start

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#3]
It would be nice, if Seth could be started minimized.

**Comment by AndyPiddock** [comment]
Interesting idea. Maybe a way to do this would be to add a right click to the icon which will display an option to shut-down from the minimized state. When this option is used then Seth would start-up minimized on next start-up.

**Comment by AndyPiddock** [comment]
This has been coded and will be in the V3.1 release.
What will happen in V3.1 is that when Seth is minimized, and you right click on the icon an answer dialogue is displayed with the option to start minimized Yes No or Cancel.

**Comment by AndyPiddock** [comment]
Completed in V3.1 release
