### ISSUE TITLE
Feature request: Store location of the icon, if stack is minimized

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#4]
I would be nice, if the location of the stack, especially when minimzed is stored.

**Comment by AndyPiddock** [comment]
I will look into this. It may need an option selected to remember the position or to revert as it does now.

**Comment by AndyPiddock** [comment]
This has been coded and will be in the V3.1 release.

**Comment by AndyPiddock** [comment]
Also added that Seth remembers its position if full size on shutdown.

**Comment by AndyPiddock** [comment]
Completed in V3.1 release
