### ISSUE TITLE
Feature request: Display message only when update is available or allow this as an option

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#5]
It would be nice, if the "your version is up to date" message could be switched of.

**Comment by AndyPiddock** [comment]
Agree. The next update will only show a message on startup if a new version is available.

**Comment by AndyPiddock** [comment]
This has been coded and will be out in V3.1

**Comment by AndyPiddock** [comment]
Completed in V3.1 release
