### ISSUE TITLE
When editor font size in LC Settings is different to the size selected in Seth, then line numbers are different in size to the text in editor

### ISSUE THREAD

**Issue by matthiasrebbe** [AndyPiddock/Seth#6]
Just noticed, that when the editor text size LC settings is other than the size selected in Seth, then the textsize of the linenumbers does not match the text size of the editor field. 

So either disable the fontsize in Seth or adjust the textsize in LC settings after changing the size in Seth.  See attached screenshot

![sethtextsize](https://user-images.githubusercontent.com/9978143/52781626-4fbe5700-304d-11e9-9f15-7da5032310be.png)

**Comment by AndyPiddock** [comment]
OH..that's an interesting catch..on my list for V3.1

**Comment by AndyPiddock** [comment]
This has been coded and will be in the V3.1 release.

![livecode_indy_2019-02-14_16-57-13](https://user-images.githubusercontent.com/37116306/52799367-f7ea1500-3079-11e9-8acd-c146d977a77f.png)
![livecode_indy_2019-02-14_16-58-57](https://user-images.githubusercontent.com/37116306/52799368-fa4c6f00-3079-11e9-8224-53bc5eda7162.png)

**Comment by AndyPiddock** [comment]
Completed in V3.1 release
