### ISSUE TITLE
Edit button should respect selected element

### ISSUE THREAD

**Issue by macMikey** [AndyPiddock/Seth#8]
Select an element in the seth list, e.g. "if"
Click the "Edit" button
Notice that "if" is not the element that is displayed, "command" is.
Also, the selected line in the list reverts to "command"
It seems that on the second time through "if" is shown, but again the selected line reverts to "command"

**Comment by AndyPiddock** [comment]
When a theme is selected the hilited element is the first in the list"commands". Once the editor is open the any element in the list selected is the one that can be edited.

Maybe I need to make an instruction note for this.

**Comment by AndyPiddock** [comment]
Now retains selected element... for V3.2

![2019-02-25_16-14-02](https://user-images.githubusercontent.com/37116306/53346992-7a938f80-3918-11e9-9c62-f680c927530e.gif)

**Comment by macMikey** [comment]
I think we have a bug.  The first time the editor is opened, regardless of which element is selected before the editor is opened, the first element is the one who's properties are in the editor (except for the name).  The hilite moves to the first element.  After the first time I open the editor, If I select an element, then open the editor again, the hilited element reverts to the top of the list, but the editor shows the properties of the element that was selected before the editor was opened.
I would argue that both of those behaviors are counterintuitive and both are bugs.

**Comment by macMikey** [comment]
So here's a screencast of the first bug.
Select an element in the list, open the editor.  Notice that the hilite in the list has moved to the top of the list.  Notice the properties displayed in the editor are for the element I originally hilited.  Change the color of the element and notice that the color has changed for the element at the top of the list.

![bug1](https://user-images.githubusercontent.com/10867016/53350267-c0d2f980-38ec-11e9-8fef-b9ce6786f216.gif)

**Comment by AndyPiddock** [comment]
Thanks for taking the time to point this  out.
If you see my screen capture above yours, you can see the selected element is retained when the editor is opened, no more jumping to the top. Fixed for the upcoming V3.2 release.

**Comment by AndyPiddock** [comment]
Included in V3.2 release.
